name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        cargo test --all-features --verbose
        cargo test --no-default-features --features reqwest_backend --verbose
        cargo test --no-default-features --features surf_backend --verbose
        cargo test --no-default-features --features ureq_backend --verbose
        cargo test --verbose
    - name: Generate docs
      run: |
        cargo doc --all-features --verbose
        cargo doc --no-default-features --features reqwest_backend --verbose
        cargo doc --no-default-features --features surf_backend --verbose
        cargo doc --no-default-features --features ureq_backend --verbose
        cargo doc --verbose
